### ISSUE TITLE
False positive: dyncdn.me

### ISSUE THREAD

**Issue by DRSDavidSoft** [RooneyMcNibNug/pihole-stuff#1]
Hi there,

I'm sure if this was intentionally blocked, but the `dyncdn.me` is a cdn used by the RarBG website and is used to load images and other site content.

```
dyncdn.me
www.dyncdn.me
```

Added in: https://github.com/RooneyMcNibNug/pihole-stuff/commit/8132cf4277a8477b50d7578988ac8107f836357f#diff-782bcd5749cc4dfa54a652ad072dcf25R18989-R18992

You can verify this by visiting any of the RarBG mirrors:
- **rarbgproxy.org**
- **rarbg.to**
- **rarbgmirror.com**

Note: RarBG is a popular and safe torrenting website.

If the `dyncdn.me` domain should not intentionally be blocked (as it does not classify under ads nor trackers), I'd like to ask to remove it from your list.

Thank you :)

**Comment by RooneyMcNibNug** [comment]
Hi there @DRSDavidSoft,

Thanks for submitting this issue and sorry it took so long to get back to you. I was unaware of the full details of that domain. I have removed the ```dyncdn.me``` URLs from my ```SNAFU``` blocklist in the latest commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/5086867c18c15131773a9ac6f2bfa0d932c70866

I'll close this now, but feel free to reach out for anything else.
