### ISSUE TITLE
ppl.i.lithium.com

### ISSUE THREAD

**Issue by p1r473** [RooneyMcNibNug/pihole-stuff#10]
This breaks pages created with Lithium such as https://www.paypal-community.com/t5/My-Money/Invalid-Card-Number-I-am-going-crazy/td-p/1544116

**Comment by RooneyMcNibNug** [comment]
Thank you for submitting this issue - `ppl.i.lithium.com` has been removed now in the following commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/a62bd7fb134057f7e8cec4e95081eba2416a3b72

Do let me know if you need anything else, and thanks again for your contributions to this list.
