### ISSUE TITLE
Invalid domains

### ISSUE THREAD

**Issue by p1r473** [RooneyMcNibNug/pihole-stuff#12]
Hello
The following have invalid/illegal characters in them and should be cleaned up

upload.zoined.com<
rubikloud.com<>www.rubikloud.com
my.ciradar.com<>www.my.ciradar.com
offers.ciradar.com<>www.offers.ciradar.com
learn.smartly.io<>www.learn.smartly.io
beta.narvar.com<>www.beta.narvar.com
storehippo.com<>www.storehippo.com

**Comment by RooneyMcNibNug** [comment]
Hi, 

Thanks for submitting this issue. I've fixed it in the following commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/45219d4a162418a1b0c1cee43fd053c78b18cd35

- JA
