### ISSUE TITLE
kaymo75663.lithium.com

### ISSUE THREAD

**Issue by p1r473** [RooneyMcNibNug/pihole-stuff#13]
Hi Rooney
Thanks for the great list
Just reporting kaymo75663.lithium.com as a false positive
It is needed for community.teamviewer.com
It is not in any other blocklists but yours

Thanks !

**Comment by RooneyMcNibNug** [comment]
Hi there, 

Thanks for reporting another issue - I appreciate all of these. I have removed this URL from the list in the following commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/b0c9bbbb4e926ca3d04215f7e1afbdb1e430d780

Stay safe.

**Comment by p1r473** [comment]
Thanks, you as well!
