### ISSUE TITLE
rogers.lithium.com

### ISSUE THREAD

**Issue by p1r473** [RooneyMcNibNug/pihole-stuff#14]
This site is required forcommunityforums.rogers.com , a forum for Rogers ISP subscribers.
Thanks!

Sidenote: yours seems to be the only blocklist out of the 450 I am using blocking these lithium sites. Where did you get these domains from?

**Comment by RooneyMcNibNug** [comment]
Hi there - To answer you side note, I think there has been some sort of domain change at some point. `lithium.com` seems to redirect to `khoros.com` now, which is the marketing site I'm looking for. I can't remember 100%, but maybe my enumeration got screwed up when I was taking a look at this marketing site a long time ago to add to my list.

For now, I have removed all of the lithium sites from my list in the following commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/7323cd80af6b42bdd2ae1b6d32b60675a836e0ec

I will add some `khoros.com` URLs soon as well, fyi.

**Comment by p1r473** [comment]
Great, thanks!!!
