### ISSUE TITLE
track*.channelsight.com

### ISSUE THREAD

**Issue by p1r473** [RooneyMcNibNug/pihole-stuff#15]
Hi,
Regarding track*.channelsight.com
The above domain is invalid (assuming the SNAFU.txt file was not meant to use wildcards)

**Comment by RooneyMcNibNug** [comment]
Hi @p1r473 ,

Thanks for catching this - I have removed in the following commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/2c7d3fe4d267df502217bd9cc111116fccb5e1d2
