### ISSUE TITLE
portal.fb.com

### ISSUE THREAD

**Issue by p1r473** [RooneyMcNibNug/pihole-stuff#16]
Hi,
I believe this is a domain for Facebook's Portal smart hub.
Yours seems to be the only blocklist in my adlist that is blocking this!
Are you sure its malicious?
Thanks!

**Comment by RooneyMcNibNug** [comment]
Oops - this was added to this list instead of my local blacklist - I have removed it from the `SNAFU` list here: https://github.com/RooneyMcNibNug/pihole-stuff/commit/7355ca831f0f9f7918dc8e384ee8e9fe52ecc421

Thanks again!
