### ISSUE TITLE
sephora.narvar.com

### ISSUE THREAD

**Issue by TheNoobWar** [RooneyMcNibNug/pihole-stuff#18]
`sephora.narvar.com` is on this list inherited from `tracking.narvar.com`.

Possible analytical tracking(?), Narvar is a shipping/delivery platform for business to consumer. Curious to see if this intended, or if there's tracking behind the scenes from this provider?

**Comment by RooneyMcNibNug** [comment]
Ah, so while this is a marketing company that uses some tracking tech, it seems that a lot of the `<company_name>.narvar.com` domains might actually used for order delivery statuses:

![image](https://user-images.githubusercontent.com/17930955/82927509-6dfc4d80-9f46-11ea-9258-8e8552a9174a.png)

I've removed all the `narvar.com` URLs from this blocklist minus the following:
```
analytics.narvar.com
instagram-endpoint.narvar.com
tracking.narvar.com
www.tracking.narvar.com
tracking-assets-prod01.narvar.com
www.tracking-assets-prod01.narvar.com
trackingimg.narvar.com
```
which I've deemed to be used for marketing/tracking purposes. Let me know how this looks to you?

**Comment by RooneyMcNibNug** [comment]
Here is the relevant commit, btw: https://github.com/RooneyMcNibNug/pihole-stuff/commit/4f454e71a1fdf390c3d5a320a2282def5218c48e

**Comment by TheNoobWar** [comment]
Looks good, thank you!
