### ISSUE TITLE
False positive: unpkg.com

### ISSUE THREAD

**Issue by DRSDavidSoft** [RooneyMcNibNug/pihole-stuff#2]
Hi there,

I believe the `unpkg.com` shouldn't be blocked, as it's a general-purpose CDN that serves [npm](https://www.npmjs.com/) packages.

```
unpkg.com
www.unpkg.com
```

Added in: https://github.com/RooneyMcNibNug/pihole-stuff/commit/8132cf4277a8477b50d7578988ac8107f836357f#diff-782bcd5749cc4dfa54a652ad072dcf25R18964-R18965

I'm not sure why this was added to your list, so if it should not intentionally be blocked (as it does not classify under ads nor trackers), I'd like to ask to remove it from your list.

**Comment by RooneyMcNibNug** [comment]
Thank you for this, and sorry for the delayed response.

I have removed the false positive on this commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/db2f00f6904056fca21cdc7ab2fc3ad05a1772d0

**Comment by DRSDavidSoft** [comment]
@RooneyMcNibNug Thank you for removing it, have a great day!
