### ISSUE TITLE
False positive - 3xqz5p387rui1hjtdv1up7lw-wpengine.netdna-ssl.com

### ISSUE THREAD

**Issue by zappe** [RooneyMcNibNug/pihole-stuff#20]
Part of demisto.com

**Comment by RooneyMcNibNug** [comment]
Hi there - thank you for submitting this issue. I have gone ahead and removed the URL in question in the commit here: https://github.com/RooneyMcNibNug/pihole-stuff/commit/a59c5db4043ec012fc9b8b738538ad2c4bcd42f9
