### ISSUE TITLE
False positive - widget.intercom.io

### ISSUE THREAD

**Issue by zappe** [RooneyMcNibNug/pihole-stuff#22]
This is used for chat software on websites

**Comment by RooneyMcNibNug** [comment]
Hi there, 

Thank you for submitting this as an issue. I have just removed this false-positive within the following commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/608ad03a79a7e15917aa878b695576cf124b24f3

Hope you have a nice weekend.
