### ISSUE TITLE
False positive - js.intercomcdn.com

### ISSUE THREAD

**Issue by zappe** [RooneyMcNibNug/pihole-stuff#23]
Used for legitimate chat software online.

**Comment by RooneyMcNibNug** [comment]
Hi there,

Thanks for this issue submission - I have gone ahead and removed the `js.intercomcdn.com` URL from the blocklist with the following commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/b884c0084e4fadfc9e3f429a32e966043dd16659

Thanks,
- Rooney
