### ISSUE TITLE
False positive - api-iam.intercom.io

### ISSUE THREAD

**Issue by zappe** [RooneyMcNibNug/pihole-stuff#25]
Part of a support solution

**Comment by RooneyMcNibNug** [comment]
Out of curiosity, can you tell me what page led you to run into this issue?

**Comment by zappe** [comment]
https://support.tink.se/sv/

It's in Swedish though

**Comment by RooneyMcNibNug** [comment]
Thank you very much, that's good enough for me to remove `api-iam.intercom.io` and `api.intercom.io` specifically - I have done so in the commit here: https://github.com/RooneyMcNibNug/pihole-stuff/commit/b9957618b42cd475e30e1d19827342dad42c3719
