### ISSUE TITLE
www.webroot.com.ssopt.net

### ISSUE THREAD

**Issue by zappe** [RooneyMcNibNug/pihole-stuff#26]
Needed for https://www.webroot.com/us/en/business/resources/system-analyzer to work

**Comment by RooneyMcNibNug** [comment]
Hi - thanks for reporting another issue!

I have just removed `www.webroot.com.ssopt.net` as well as `cartapi.webroot.com.ssopt.net` from this list. The link you provided was helpful for context.

The changes have been made in the commit here: https://github.com/RooneyMcNibNug/pihole-stuff/commit/3b1355738d0f6ed8e7204b2c0ab43622f0752c2b
