### ISSUE TITLE
SNAFU invalid entries

### ISSUE THREAD

**Issue by lightswitch05** [RooneyMcNibNug/pihole-stuff#27]
Hello, thank you for your SNAFU list. I have found a few invalid entries that you might not be aware of:

### Space in domain name:

* `profile- eu.exe.bid`
* `http win.staticstuff.net`
* `ipb0c .voluumtrk3.com`
* `wood. www.ispot.tv`
* `pearsonn rpush.cogocast.net`
* `m e.maillist-manage.com`

### Leading `-`

According to [rfc3696](https://tools.ietf.org/html/rfc3696) 

> If the hyphen is used, it is not permitted to appear at
   either the beginning or end of a label.

* `-x3.vindicosuite.com`

### Leading `.`

You might have these entries in here on purpose. If so, please ignore.

* `.yieldoptimizer.com`
* `.nemosys.ws.markmonitor.com`
* `.pagefair.net`
* `.qa2.la.razorfish.com`

**Comment by RooneyMcNibNug** [comment]
Thank you very much for submitting this issue - I have gone ahead and made respective changes in the following commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/744ffa6cf449676f43d0e8ea868a124a0478c9c8

Here is a high-level breakdown of the changes made:

- Fixed all domains applicable in `Space in Domain name` section, else deleted.
- Deleted `-x3.vindicosuite.com`
- Deleted all domains in `Leading .` section (they were not added purposefully)

Regards,
- Rooney
