### ISSUE TITLE
qs976j62-android.mobile-sdk-api.intercom.io False Positive

### ISSUE THREAD

**Issue by maisonmdsgreen** [RooneyMcNibNug/pihole-stuff#28]
Chat bank inter use qs976j62-android.mobile-sdk-api.intercom.io

Thanks
Maison

**Comment by RooneyMcNibNug** [comment]
Hi there, 

Thank you for submitting this issue. I have gone ahead and removed the requested URL in the following commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/bdf601b4632fdb1673ff8562e93ffc1bec73a7ed

Regards,
Rooney
