### ISSUE TITLE
nexus-websocket-a.intercom.io

### ISSUE THREAD

**Issue by zappe** [RooneyMcNibNug/pihole-stuff#29]
Used for intercom chat on Vilfo devices

**Comment by RooneyMcNibNug** [comment]
Hi there, 

Thank you for submitting this issue. I have removed thefollowing domains from this list:

```
nexus-test-websocket-a.intercom.io
nexus-test-websocket-b.intercom.io
nexus-testing.intercom.io
nexus-websocket-a.intercom.io
nexus-websocket-b.intercom.io
www.nexus-websocket-b.intercom.io
www.nexus-websoocket-b.intercom.io
www.nexuswebsocketb.intercom.io
```
This has been done via the following commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/9bd215d9bdea96a7acbabbd1f99004a391b3bb5c

Let me know if you run into any other issues, as there are still some nexus-specific `intercom.io` subdomains included within this blocklist.

Thanks.
