### ISSUE TITLE
False positive: dyjpb62732.i.lithium.com

### ISSUE THREAD

**Issue by Ghalid** [RooneyMcNibNug/pihole-stuff#3]
dyjpb62732.i.lithium.com is required to view github.community threads correctly (with it blocked, formatting looks incorrect).

**Comment by DRSDavidSoft** [comment]
Also some other false positives (and CNAMEs that point to them):

```
fyrhh23835.lithium.com
community.checkpoint.com
aruba.lithium.com
aruba.i.lithium.com
community.arubanetworks.com
techcommunity.microsoft.com
gxcuf89792.lithium.com
gxcuf89792.i.lithium.com
sonyeu1.lithium.com
sonymobile.lithium.com
sonyeu1.i.lithium.com
sonymobile.i.lithium.com
lnv.lithium.com
lnv.i.lithium.com
forums.lenovo.com
i.lithium.com
kxiwq67737.lithium.com
kxiwq67737.i.lithium.com
community.cisco.com
tnckb94959.lithium.com
community.atlassian.com
```

**Comment by RooneyMcNibNug** [comment]
Hi both - thanks for these, I have removed the mentioned false-positives in the following commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/782ccf0a6f0fa83020234fb52af74f0425fb6a18
