### ISSUE TITLE
Stray <BR>

### ISSUE THREAD

**Issue by yitzhaq** [RooneyMcNibNug/pihole-stuff#32]
This looks like a minor bug:

https://github.com/RooneyMcNibNug/pihole-stuff/blob/c854f981d4932cebc76037e929bbc42da97ad609/SNAFU.txt#L39517

Thanks for your work.

**Comment by RooneyMcNibNug** [comment]
Hi there, 

Thank you for filing this. Someone else also made a PR pointing out the same issue, which has already been merged here: https://github.com/RooneyMcNibNug/pihole-stuff/commit/aa21c83eb10b7f50352cc556205b6c872296c5ed

I appreciate your help, and stay safe.
- JA
