### ISSUE TITLE
tracking.narvar.com

### ISSUE THREAD

**Issue by p1r473** [RooneyMcNibNug/pihole-stuff#34]
Hi
This is parcel tracking, not spyware tracking :)

**Comment by RooneyMcNibNug** [comment]
Hi there, 

Thank you for submitting this issue. I have verified that this is indeed a delivery status URL, so I have gone ahead and removed a few of the `narvar.com` URLs in question here from my list as a false-positive with this commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/f37ea4323dec588218a27f2a0e3ee28858638fa2

Regards,
Rooney
