### ISSUE TITLE
pubnub.com

### ISSUE THREAD

**Issue by p1r473** [RooneyMcNibNug/pihole-stuff#37]
This is a real-time API to build engaging remote experiences using in-app chat, push notifications, etc
pubsub-rc.pubnub.com is a CNAME for ringcentral.pubnubapi.com which is RingCentral, a teleconferencing system
I dont believe blocking an API is a good idea. Rather, we should block malicious apps that may leverage an API.

![image](https://user-images.githubusercontent.com/9235633/126562804-51ec234d-242b-4c49-a1b7-cd2fa50c7d85.png)

**Comment by RooneyMcNibNug** [comment]
Thank you very much for submitting this issue.

I have gone ahead and removed a majority of the `pubnub.com` subdomains previously located within my `SNAFU` list, leaving only a few remaining which seem to be non-critical and might be used fro tracking users in some way or another.

You can find the relevant commit here: https://github.com/RooneyMcNibNug/pihole-stuff/commit/cc9abfc887601fe214dbf65d009c64ed2203cd36

Have a good one, 
- Rooney
