### ISSUE TITLE
rtc-v2-ms1.bitrix24.com

### ISSUE THREAD

**Issue by JailSeed** [RooneyMcNibNug/pihole-stuff#39]
Hello! If this domain is blocked then online chats based on Bitrix24 services don't work. Found out that while trying to consult in online shop website.

**Comment by RooneyMcNibNug** [comment]
Hi there @JailSeed ,

Thank you for this issue submission, I appreciate it.

I have removed both `rtc-v2-ms1.bitrix24.com` and `rtc-v2-ms2.bitrix24.com` from the `SNAFU` list now. This has been accomplished in the following commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/6ba6544ac8fa87aea9325ef1d98b7cca050d6778

If you run into any other issues please do let me know.

Safe travels,
_Rooney_
