### ISSUE TITLE
False positive -dns.msftncsi.com

### ISSUE THREAD

**Issue by sml156** [RooneyMcNibNug/pihole-stuff#4]
dns.msftncsi.com is used by Microsoft Windows as part of it's Network Connectivity Status Indicator tests.

It is also used by some router manufactures.

**Comment by RooneyMcNibNug** [comment]
Thanks for finding this, and apologies for the late reply.

I have removed this false-positive in the following commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/6b0f4f7ccc9a76d40ee22da70c15981a2d403d3f
