### ISSUE TITLE
cdn.ravenjs.com

### ISSUE THREAD

**Issue by gyCfjSnO** [RooneyMcNibNug/pihole-stuff#43]
Can't access the login portal for my energy provider to pay and view my bills when ```cdn.ravenjs.com``` is blocked. Energy provider is ```https://www.reampedenergy.com.au/```

**Comment by RooneyMcNibNug** [comment]
Hi @gyCfjSnO - thank you very much for submitting this issue. It helps me keep this blocklist clean and functioning properly.

I'm not sure how these URLs got added, tbh, but I have gone ahead and removed the following from my `SNAFU` blocklist:

```
ravenjs.com
www.ravenjs.com
cdn.ravenjs.com
```

This has been completed in the following commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/f62d0804b267c7b2c4f57d912d4c82f2d88ede72

This should help you moving forward, but let me know if you notice any other issues.

Regards,
_Rooney_
