### ISSUE TITLE
Odd whitespace in entry

### ISSUE THREAD

**Issue by bronger** [RooneyMcNibNug/pihole-stuff#44]
https://github.com/RooneyMcNibNug/pihole-stuff/commit/db6777dd5c851b67345ebebf17b5edfccc64b491 introduced the spurious line `2 script.crazyegg.com`. I assumed this was illegal but I’m not an expert. Is it meant this way?

**Comment by RooneyMcNibNug** [comment]
Hi @bronger  - thanks for this issue submission!

I'm not an expert on `rfc3986` or anything either, but I would presume that a space in a URI like this would make it illegal as well.. I used [Sublist3r](https://github.com/aboul3la/Sublist3r) for this particular sub-domain enumeration, so I wonder if something went wrong there.

Regardless, I have removed the referenced URL as well as one other possibly illegal one in the following commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/051959b2dd1f919504d1d3551cf142493f2da5c9

Regards,
_Rooney_
