### ISSUE TITLE
False Positive: prod-live-chat.sprinklr.com

### ISSUE THREAD

**Issue by Tricky-M** [RooneyMcNibNug/pihole-stuff#45]
`prod-live-chat.sprinklr.com` is used on sites such as [samsung.com](https://www.samsung.com/uk/support/contact/#shop-support) in order to open an online chat with product support. Suspect this service is used on the other sites too.

There are other sprinklr.com entries in the list, some of which may be non-tracking, however just the above needed allowing to enable the chat window to open.

**Comment by RooneyMcNibNug** [comment]
Thanks for reporting this, @Tricky-M 

I have gone ahead and removed the following URLs from the blocklist:

```
prod.sprinklr.com
prod-live-chat.sprinklr.com
prod-live-chat-mqtt.sprinklr.com
```

I believe, based on what you've stated, this should clear up your issue. This has been achieved in the following commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/659cb5e02c2f54cfc429f507b60bc06fbfbc8d5b

Let me know if you still have any issues, please.
