### ISSUE TITLE
api.usercentrics.eu

### ISSUE THREAD

**Issue by wassereimer86** [RooneyMcNibNug/pihole-stuff#49]
Hi there,

thank you for your work!

api.usercentrics.eu is needed so that the Andoid App "Flaschenpost" is working. Please have a look at it. :)

**Comment by RooneyMcNibNug** [comment]
Hi @wassereimer86 !

Thank you fro submitting this issue. It helps keep the list strong.

I have removed the following URLs from the SNAFU blocklist:

```
api.usercentrics.eu
cached.api.usercentrics.eu
consents.api.usercentrics.eu
app.usercentrics.eu
```

These changes have been made here: https://github.com/RooneyMcNibNug/pihole-stuff/commit/3f6594d19f9ff99da40aba9a4f7fbf361090f861

This should clear up your issue, but let me know if you run into any other issues please.

Safe surfing,
_Rooney_
