### ISSUE TITLE
sp-ao.shortpixel.ai

### ISSUE THREAD

**Issue by PRSXFENG** [RooneyMcNibNug/pihole-stuff#51]
In use by

https://dynabook.com.my/

Blocking this results in broken images

**Comment by RooneyMcNibNug** [comment]
Hi @PRSXFENG - thank you for submitting this issue, I appreciate it.

I tested and you are correct - whitelisting that subdomain makes the site work much better.

I have removed it in the following commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/7fd4b5b56d66de96c8f24abaf630d8f7fd31d364

You should be fine after a `pihole -g` now. Let me know if you need anything else.
_Rooney_
