### ISSUE TITLE
SNAFU: Please Remove the following URLs from the list

### ISSUE THREAD

**Issue by JNR8** [RooneyMcNibNug/pihole-stuff#53]
Hi,

Whilst trying to make bank payments today I was thwarted several times because the following domains are used by banks in the UK (possbily globally) to authenticate card payments online.  I;ve whitelisted these domains in my PiHole setup, but for all theother out there it may be prudent to remove these domains from the SNAFU.txt block list:

- authentication.cardinalcommerce.com
- geoissuer.cardinalcommerce.com
- geo.cardinalcommerce.com
- writer.cardinalcommerce.com
- centinalapi.cardinalcommerce.com

Thanks,

**Comment by RooneyMcNibNug** [comment]
Hi @jennec ,

Thank you for submitting this. There were some subdomains from this domain removed [after this recent other issue was filed](https://github.com/RooneyMcNibNug/pihole-stuff/issues/52), but I am going to go ahead and remove all of the remaining from this domain just to be safe:

```
1geo.cardinalcommerce.com
0geo.cardinalcommerce.com
geo.cardinalcommerce.com
```

I want this list to be comprehensive, but more than anything I don't want it to break things.

Let me know if you need anything else, but this should be all solved with this: https://github.com/RooneyMcNibNug/pihole-stuff/commit/7f51575f599b5c753bb919a8ba1f83b09124c490

Safe surfing,
_Rooney_
