### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by Tinsus** [RooneyMcNibNug/pihole-stuff#58]
could you please fix the following two typos/non valid domain in your list?

[-] Total Unique Subdomains Found: 77
wealthfidelitylimited,cin

**Comment by RooneyMcNibNug** [comment]
Hi @Tinsus - thank you for reporting this. I have gone ahead and removed this URL from the blocklist with this commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/1aacb321057471d6bd29af10e44a468388460b5c

I appreciate you catching this. 
-Rooney
