### ISSUE TITLE
Incorrect lines

### ISSUE THREAD

**Issue by redneckeyeball** [RooneyMcNibNug/pihole-stuff#59]
Please check the line that holds
platform.twitter.com

This is what it looks like
api-glb-sjc.smoot.apple.comapi.acompli.netapi.mixpanel.comapi.segment.ioapi.twitch.tvapi.twitter.comapiservices.krxd.netapps.itunes.comas.jivox.com
as.jivox.comas.jivox.com
apple-finance.query.yahoo.comas.jivox.com
evs.jivox.comevs.jivox.com
playercdn.jivox.complayercdn.jivox.com
platform.twitter.complayercdn.jivox.com
pxl.jivox.compxl.jivox.com
creativescdn.jivox.com

There are several lines that have no breaks. And playercdn.jivox.com is listed multiple times.

Also I believe that platform.twitter.com should not be in this list. I had to whitelist it to avoid errors on mobile devices.

**Comment by RooneyMcNibNug** [comment]
Hi @redneckeyeball - thanks for submitting this. It does indeed look like those lines are a bit mangled.. not sure how that happened, but this should be fixed with https://github.com/RooneyMcNibNug/pihole-stuff/commit/b5bbb7dafe773908e40d52223d2548c4e0170b28 now.

Cheers!
-Rooney
