### ISSUE TITLE
sockjs.pusher.com

### ISSUE THREAD

**Issue by Ghalid** [RooneyMcNibNug/pihole-stuff#6]
I saw `sockjs.pusher.com` in my blocked query logs, and I was wondering whether this is a FP or not. It looks like a service used for push notifications, chat, etc. (see https://pusher.com), but I'm unsure whether it is blocked for being a tracking domain/some other reason.

**Comment by RooneyMcNibNug** [comment]
Hi there - thanks for flagging this. I think that was added by accident - it has been removed from the list now with the following commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/6dd8a812a0d5aae8a74b989a38031a03e3da6013

Thanks.
