### ISSUE TITLE
assets.vidyard.com breaks Vidyard

### ISSUE THREAD

**Issue by p1r473** [RooneyMcNibNug/pihole-stuff#60]
assets.vidyard.com breaks Vidyard
![image](https://user-images.githubusercontent.com/9235633/230411389-82782d4b-8200-4b50-9b95-995d67a5254a.png)

**Comment by RooneyMcNibNug** [comment]
Hi @p1r473 , 

Thanks for submitting this issue (and for the helpful screenshot as well) - I've just fixed this with https://github.com/RooneyMcNibNug/pihole-stuff/commit/25a144ef7da649d739532917b7dc72bfae8515c3 so you should be good here now.

Regards,
_Rooney_
