### ISSUE TITLE
Blocking click.pstmrk.it causes trouble with legitimate email

### ISSUE THREAD

**Issue by bronger** [RooneyMcNibNug/pihole-stuff#61]
I filed a request for an ebook download at a respectable company and received an email with a download link. This download link used click.pstmrk.it as a proxy. I whitelisted that domain on my side, but possibly this makes sense also on your list.

**Comment by RooneyMcNibNug** [comment]
Hmm yeah this is a tricky one @bronger . Personally, I would like to leave any of these types of `click.*` email tracker subdomains in the list.

I think if more of these come up as fundamentally resolution to something important from email > browser, I would be interested to know.

**Comment by bronger** [comment]
I doubt that we can gather enough information for that. The question is: Does it more harm than good? In my case, a document I needed became inaccessible, so possible tracking would have been the lesser evil.

But I do not know who else uses that proxy. It may well be that mostly it is used by ads service or other dispensable material.

My approach is that false positives are seldom, but if they happen, they are really annoying. So I rather remove one domain from my 3 Mio domains list. YMMV.

**Comment by RooneyMcNibNug** [comment]
These email one are hard in particular. It seems a lot of 3rd parties are switching from pixels to these lately too..

Personally, I am the type of grouch that will get hit by one of these failed email link resolutions and just use something like https://urlex.org/ to get the "un-tracked" link, but I would never expect others to do the same too much.

I try and put the work in for this list to be expansive and catch a lot of nasty domains that aren't picked up on other popular ones, but more-so I want things to work for people. I think you expressing that you "couldn't access a document you needed" helps me think that its not worth keeping this domain in the blocklist, so thank you for that.

I've removed the single URL in this commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/5393c99f19ac3e7a613919bd9dab3fccf0431b65

Hopefully this will help others not encounter the issue, so again, I appreciate this. Its only on URL removed after all, and there will be plenty others added as I continue to build this out.

Safe travels,
_Rooney_
