### ISSUE TITLE
tsfe.trafficshaping.dsp.mp.microsoft.com False Positive

### ISSUE THREAD

**Issue by gorbiWTF** [RooneyMcNibNug/pihole-stuff#63]
[As per Microsoft](https://learn.microsoft.com/en-us/windows/privacy/manage-windows-11-endpoints): "The following endpoint is used for content regulation. If you turn off traffic for this endpoint, the Windows Update Agent will be unable to contact the endpoint and fallback behavior will be used. This may result in content being either incorrectly downloaded or not downloaded at all."

- tsfe.trafficshaping.dsp.mp.microsoft.com

I think it should be allowed, however I understand if someone else doesn't think so.

**Comment by RooneyMcNibNug** [comment]
I agree with your assessment here @gorbiWTF - thanks for submitting this and linking to MSFT documentation to support, its much appreciated. I have removed this specific URL from the `SNFU` blocklist with the following commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/d894c7aeea133f24bf3241c7f531d89633abb5f0

Cheers,
_Rooney_
