### ISSUE TITLE
ipinfo.io

### ISSUE THREAD

**Issue by ikheetjeff** [RooneyMcNibNug/pihole-stuff#65]
Hi,

Why is the full domain name "ipinfo.io" also listed? Ipinfo.io itself is a fairly reliable site, right?

**Comment by RooneyMcNibNug** [comment]
Hi @ikheetjeff , 

Thanks for this issue - yes, good call. It does look like this is mostly benign. I'm not sure why I used the full enumeration here, so I am removing everything besides `pixel.ipinfo.io` which I assume is being used for tracking pixels.

This has been done in the following commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/d7c4b49f2171016bd89f0187ae96e86bc5729679

Take care,
_Rooney_
