### ISSUE TITLE
js.chargebee.com

### ISSUE THREAD

**Issue by p1r473** [RooneyMcNibNug/pihole-stuff#66]
This is the Javascript server for chargebee, an online payments processor
This broke payments on ecommerce site such as signalrgb.com

**Comment by RooneyMcNibNug** [comment]
Hi again, @p1r473! Thanks for this - I have removed that single subdomain from my list with the latest commit at https://github.com/RooneyMcNibNug/pihole-stuff/commit/41892aa609b9d9a90b27fddc6b986e6209b2bbff

Let me know if you need anything else.
_Rooney_
