### ISSUE TITLE
*.informatica.com

### ISSUE THREAD

**Issue by daberlin** [RooneyMcNibNug/pihole-stuff#67]
Should this domain really be blocked? Why?

**Comment by RooneyMcNibNug** [comment]
@daberlin Hi - thanks for submitting this issue.

That page _does_ look pretty benign, so I have gone ahead and removed most of the subdomains for that URL from the SNAFU blocklist, leaving only a few which look like they might be used for tracking purposes. 

This has been done in the following commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/c8e8f1155c839f2449e7411b8d10edc1010d58cf
