### ISSUE TITLE
SNAFU: false positive "www.techtarget.com"

### ISSUE THREAD

**Issue by daberlin** [RooneyMcNibNug/pihole-stuff#68]

**Comment by RooneyMcNibNug** [comment]
Hi @daberlin - thanks for submitting this.

Respectfully, I do consider this to be a proper domain that should be blocked. They are tracking user "insights" and hoovering data through some of their URLs.

Here are some other sources that show the type of work they do:

- https://x.com/TechTarget
- https://www.linkedin.com/company/techtarget
- https://urlscan.io/result/626dbe40-ff7c-4ca1-8a5b-3fcf54aab3c9/ 

I am going to close this and keep this URL on the blocklist, but feel free to allowlist this particular domain on your end if you would like to continue using `SNAFU` with pi-hole or any other blocking system.

Thanks for your understanding.
