### ISSUE TITLE
Your own addition?

### ISSUE THREAD

**Issue by spirillen** [RooneyMcNibNug/pihole-stuff#69]
Hi, I found your project via `https://github.com/maravento/blackweb/edit/master/bwupdate/bwupdate.sh` as I'm updating my [Hosts-source](https://github.com/external-sources/hosts-sources) library to add more source to search among. But I'm in doubt whether you just merge external source or you actually keeps and maintain your own lists. 

In case you maintain your own lists, which would that be?

**Comment by RooneyMcNibNug** [comment]
Hi @spirillen! Thanks for submitting this question.

I _do_ maintain this myself in my spare time - in fact the origin was that some popular lists that were shipping with things like pi-hole were not capturing as much as I would have liked from common domains. Going down rabbit-holes like this in my spare time as well to capture lots of things to block: https://rooneymcnibnug.github.io/privacy/2022/08/19/tracker-domain-enum-FF-N-NP-pt2.html

I hope this answers your question? The tl;dr is basically **I run this on my own and don't really ingress much anything from other existing lists**. I check to see if it exists in [blocklists that I use](https://github.com/RooneyMcNibNug/pihole-stuff/blob/master/adlists_config.txt) before I even decide to add it to my `SNAFU` blocklist as well.

Taking a look at some of your work by the way, looks awesome. :)

**Comment by RooneyMcNibNug** [comment]
Oops, I missed your last part - the `SNAFU` list is the one that I consistently update myself (weekly, on average): https://github.com/RooneyMcNibNug/pihole-stuff/blob/master/SNAFU.txt

There are some others in that same repo that have been pulled from other sources an enumerated, but they are more set in stone.

Hope that helps.

**Comment by spirillen** [comment]
Your project have been [added](https://github.com/external-sources/hosts-sources/commit/c3254c9d273f6766223e537798309487a0a2ad65#diff-86e5b0318b37a34efb3caf9121d42ce93fb2506cbf1766d86d2119f16b7126e4R4) to the search tool :)  thanks for your replies.

**Comment by RooneyMcNibNug** [comment]
Thanks @spirillen ! I just did a PR though, since I think the URL added for `SNAFU` is incorrect with that commit you linked: https://github.com/external-sources/hosts-sources/pull/5

**Comment by spirillen** [comment]
Yeah, I don't know, but Ubuntu 24 and Debian 12 have a lot of Copy/paste issues, the clipboard just sucks. Thanks for spotting this and fixing it 👍🏻

**Comment by RooneyMcNibNug** [comment]
NP, thanks for your reaching out again! Closing this now, safe surfing.
