### ISSUE TITLE
js.hsforms.net

### ISSUE THREAD

**Issue by p1r473** [RooneyMcNibNug/pihole-stuff#7]
This domain prevents content on pages from displaying
EG Blocks text from loading
https://forbesrealestatecouncil.com/app/
and
https://www.purposeinvest.com/canadians

**Comment by RooneyMcNibNug** [comment]
Hi, 

Thank you for submitting this. I have gone ahead and removed ```js.hsforms.net``` from the blocklist in this commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/9c3bf6f2cc6cd65ee39b83e726490b0ddcc59361

Feel free to file another issue if you find anything that breaks your browsing experience.
