### ISSUE TITLE
unsubscribe.mailerlite.com

### ISSUE THREAD

**Issue by p1r473** [RooneyMcNibNug/pihole-stuff#8]
This domain is needed to unsubscribe from emails on mailerlite

**Comment by RooneyMcNibNug** [comment]
Hi, 

Thank you for catching this. I have removed this single subdomain with this commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/c4faef6bf44be730c35f63c22970962949fdf9ad

- J.A.
